# Generated by Django 4.1.3 on 2022-11-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COMMAND',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=400)),
                ('k_command', models.CharField(max_length=400)),
                ('description', models.TextField()),
            ],
        ),
    ]
